services:
  - type: web
    name: ecomm-web
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: >
      sh -c "python manage.py migrate && \
             python manage.py collectstatic --noinput && \
             gunicorn ecomm.wsgi:application"
    envVars:
      - fromGroup: ecomm-env

  - type: worker
    name: ecomm-celery
    env: docker
    plan: free
    autoDeploy: true
    startCommand: celery -A ecommerce worker --loglevel=info
    envVars:
      - fromGroup: ecomm-env